name: create-clear package publish

on:
  push:
    branches: ["create-clear"]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
      - uses: actions/checkout@v4

      - name: Setup Node
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Publish create-clear
        working-directory: packages/create-clear
        env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --no-git-checks
