name: clear-fetch pkg publish

on:
  pull_request:
    branches:
      - master
    paths:
      - 'packages/clear-fetch/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.npm_token }}
